#!/bin/bash
# Lock the screen

lock() {
    # betterlockscreen -l dimblur
    i3lock \
        -Ci "/tmp/lockimg.png" \
        --time-pos="x+120:h-120" --time-size=130 --time-str="%R" \
        --date-pos="x+130:h-90" --date-size=20 --date-str="%A, %d %B %Y" \
        --clock --date-align 1 --time-align 1 \
        --inside-color=00000000 --ring-color=ffffffff --line-uses-inside \
        --keyhl-color=1768b7ff --bshl-color=1768b7ff --separator-color=00000000 \
        --insidever-color=00000000 --insidewrong-color=d23c3dff \
        --ringver-color=ffffffff --ringwrong-color=ffffffff \ #--indpos="x+280:h-70" \
        --radius=20 --ring-width=4 --verif-text="" --wrong-text="" --noinput-text="" \
        --verif-color=ffffffff --time-color=ffffffff --date-color=b8b6b6 \
        --time-font="sans-serif" --date-font="sans-serif" --layout-font="sans-serif" 
}

if [ "$1" == "off" ]
then
    lock & 
    sleep 2s
    $(xset dpms force off)
else
    lock
fi 
