#!/bin/bash

set -e
filepath=/run/user/1000/wallpaper_paused

shuffle() {
    bg=$(find "/home/qwerty/Saved Pictures/Wallpapers/Desktop" -type f -and -not -iname '*.gif' | shuf -n 1)
    echo "Found wallpaper $bg" >&2
    echo "$bg"
}

set_wp() {
    wallpaper=$(shuffle)
    betterlockscreen -u "$wallpaper"
    echo "Set lockscreen to $(basename "$wallpaper")" >&2
    feh --bg-fill "$wallpaper"
    echo "Set wallpaper to $(basename "$wallpaper")" >&2
}

if [ ! -e "$filepath" ] || [ "$1" == "force"  ]; then
    if [ "$1" == "force" ]; then
        dunstify -a "$(hostname)@$USER" "Randomising wallpaper"
    fi
    set_wp
fi
